## You should change each of the following fields
## to customize your blog

title: Presidents and the Economy
description: "Which political party in the White House is better for the economy?" 
author: Zach Perry
author_description: "Hello" 

url: https://zach-321.github.io ## change this to https://yourusername.github.io
baseurl: /my-blog2 ## change this to the name of your blog repository
header_image: /assets/img/headerimg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  https://github.com/Zach-321
    twitter: 
    facebook: 
    email: 
    linkedin: 
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




